palette = "dracula"
add_newline = false

format = """
$username\
$directory\
$git_branch\
$git_status\
$nodejs\
$time\
$line_break\
$character
"""

[palettes.dracula]
background = "#282a36"
current_line = "#44475a"
foreground = "#f8f8f2"
comment = "#6272a4"
cyan = "#8be9fd"
green = "#50fa7b"
orange = "#ffb86c"
pink = "#ff79c6"
purple = "#bd93f9"
red = "#ff5555"
yellow = "#f1fa8c"

[username]
show_always = true
style_user = "bold cyan"
style_root = "bold red"
format = "[ $user ]($style)"

[directory]
style = "bold green"
format = "[ $path ]($style)"
truncate_to_repo = false
truncation_length = 4

[git_branch]
symbol = ""
style = "bold pink"
format = "[ $symbol $branch ]($style)"

[git_status]
style = "bold red"
format = "[ $all_status$ahead_behind ]($style)"

[nodejs]
style = "bold purple"
format = "[ $symbol $version ]($style)"

[time]
disabled = false
time_format = "%H:%M"
style = "bold yellow"
format = "[ ♥ $time ]($style)"

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"
vimcmd_symbol = "[<](bold cyan)"
