# This file is generated by shared/nushell/generate_externs.py.
# Do not edit manually.

def __terminal_bootstrap_claude_permission_modes [] {
  ["acceptEdits", "auto", "bypassPermissions", "default", "dontAsk", "plan"]
}

extern "claude" [
  prompt?: string
  ...args: string
  --add-dir: string
  --agent: string
  --agents: string
  --allow-dangerously-skip-permissions
  --allowedTools: string
  --allowed-tools: string
  --append-system-prompt: string
  --bare
  --betas: string
  --brief
  --chrome
  -c
  --continue
  --dangerously-skip-permissions
  -d: string
  --debug: string
  --debug-file: string
  --disable-slash-commands
  --disallowedTools: string
  --disallowed-tools: string
  --effort: string
  --exclude-dynamic-system-prompt-sections
  --fallback-model: string
  --file: string
  --fork-session
  --from-pr: string
  -h
  --help
  --ide
  --include-hook-events
  --include-partial-messages
  --input-format: string
  --json-schema: string
  --max-budget-usd: string
  --mcp-config: string
  --mcp-debug
  --model: string
  -n: string
  --name: string
  --no-chrome
  --no-session-persistence
  --output-format: string
  --permission-mode: string@__terminal_bootstrap_claude_permission_modes
  --plugin-dir: string
  -p
  --print
  --remote-control-session-name-prefix: string
  --replay-user-messages
  -r: string
  --resume: string
  --session-id: string
  --setting-sources: string
  --settings: string
  --strict-mcp-config
  --system-prompt: string
  --tmux
  --tools: string
  --verbose
  -v
  --version
  -w: string
  --worktree: string
]

extern "claude agents" [
  ...args: string
  -h
  --help
  --setting-sources: string
]

extern "claude auth" [
  ...args: string
  -h
  --help
]

extern "claude auto-mode" [
  ...args: string
  -h
  --help
]

extern "claude doctor" [
  ...args: string
  -h
  --help
]

extern "claude install" [
  target?: string
  ...args: string
  --force
  -h
  --help
]

extern "claude mcp" [
  ...args: string
  -h
  --help
]

extern "claude plugin" [
  ...args: string
  -h
  --help
]

extern "claude plugins" [
  ...args: string
  -h
  --help
]

extern "claude setup-token" [
  ...args: string
  -h
  --help
]

extern "claude update" [
  ...args: string
  -h
  --help
]

extern "claude upgrade" [
  ...args: string
  -h
  --help
]
