#!/usr/bin/env python3
from __future__ import annotations

import argparse
import re
import subprocess
from pathlib import Path

CLI_CONFIGS: dict[str, dict] = {
    "openclaude": {
        "subcommands": [
            "agents",
            "auth",
            "doctor",
            "install",
            "mcp",
            "plugin",
            "plugins",
            "setup-token",
            "update",
            "upgrade",
        ],
        "target_optional_subcommands": {"install"},
        "permission_modes": [
            "acceptEdits",
            "bypassPermissions",
            "default",
            "dontAsk",
            "plan",
        ],
    },
    "claude": {
        "subcommands": [
            "agents",
            "auth",
            "auto-mode",
            "doctor",
            "install",
            "mcp",
            "plugin",
            "plugins",
            "setup-token",
            "update",
            "upgrade",
        ],
        "target_optional_subcommands": {"install"},
        "permission_modes": [
            "acceptEdits",
            "auto",
            "bypassPermissions",
            "default",
            "dontAsk",
            "plan",
        ],
    },
}


def run_help(command: str, *args: str) -> str:
    result = subprocess.run(
        [command, *args, "--help"], check=True, capture_output=True, text=True
    )
    return result.stdout


def parse_options(help_text: str) -> list[tuple[str, bool]]:
    options: list[tuple[str, bool]] = []
    seen: set[str] = set()
    in_options = False
    for line in help_text.splitlines():
        stripped = line.strip()
        if stripped == "Options:":
            in_options = True
            continue
        if in_options and stripped.startswith("Commands:"):
            break
        if not in_options or not stripped.startswith("-"):
            continue
        left = re.split(r"\s{2,}", stripped, maxsplit=1)[0]
        takes_value = " <" in left or " [" in left
        for part in [piece.strip() for piece in left.split(",")]:
            if part.startswith("-"):
                token = part.split()[0]
                if token not in seen:
                    seen.add(token)
                    options.append((token, takes_value))
    return options


def render_option(token: str, takes_value: bool, permission_fn: str) -> str:
    if token == "--permission-mode":
        return f"  {token}: string@{permission_fn}"

    if takes_value:
        return f"  {token}: string"

    return f"  {token}"


def render_extern(
    name: str,
    options: list[tuple[str, bool]],
    permission_fn: str,
    is_root: bool,
    target_optional: bool = False,
) -> list[str]:
    lines = [f'extern "{name}" [']
    if is_root:
        lines.append("  prompt?: string")
    if target_optional:
        lines.append("  target?: string")
    lines.append("  ...args: string")
    for token, takes_value in options:
        lines.append(render_option(token, takes_value, permission_fn))
    lines.append("]")
    return lines


def build_script(command: str) -> str:
    config = CLI_CONFIGS[command]
    permission_fn = (
        f"__terminal_bootstrap_{command.replace('-', '_')}_permission_modes"
    )
    permission_values = ", ".join(f'"{mode}"' for mode in config["permission_modes"])

    lines = [
        "# This file is generated by shared/nushell/generate_externs.py.",
        "# Do not edit manually.",
        "",
        f"def {permission_fn} [] {{",
        f"  [{permission_values}]",
        "}",
        "",
    ]

    root_options = parse_options(run_help(command))
    lines.extend(
        render_extern(command, root_options, permission_fn, is_root=True)
    )
    lines.append("")

    for subcommand in config["subcommands"]:
        options = parse_options(run_help(command, subcommand))
        target_optional = subcommand in config["target_optional_subcommands"]
        lines.extend(
            render_extern(
                f"{command} {subcommand}",
                options,
                permission_fn,
                is_root=False,
                target_optional=target_optional,
            )
        )
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--command", required=True, choices=sorted(CLI_CONFIGS.keys()))
    parser.add_argument("--output", required=True)
    args = parser.parse_args()

    output_path = Path(args.output)
    output_path.write_text(build_script(args.command))


if __name__ == "__main__":
    main()
